/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.20
    max_hamming: 0
    qos_profile: default
    pose_estimation_method: pnp
    profile: false
    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    tag:
      ids: [0, 1, 2, 3]
      frames:
        - apriltag_36h11_00000
        - apriltag_36h11_00001
        - apriltag_36h11_00002
        - apriltag_36h11_00003
      sizes: [0.20, 0.20, 0.20, 0.20]
