/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.20
    max_hamming: 0
    qos_profile: default
    pose_estimation_method: pnp
    profile: false

    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    tag:
      ids: [0]
      frames: [apriltag_36h11_00000]
      sizes: [0.20]
